django05/App/urls.py
# -*- coding: utf-8 -*-
# @File    : urls.py
# 描述     ：
# @Time    : 2020/1/15 9:08
# @Author  :
# @QQ

from django.contrib import admin
from django.urls import path

from App import views
#写上app_name
app_name='App'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('mark/',views.reply,name='mark'),
    path('home/',views.index,name='home'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
]

django05/django05/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #包含了应用App的路由
    path('App/', include("App.urls")),
]

django05/App/models.py
from django.db import models

# Create your models here.
class User(models.Model):

    username=models.CharField(max_length=60,unique=True)
    password=models.CharField(max_length=128)
    email=models.CharField(max_length=128)
    phone=models.CharField(max_length=128)

    class Meta:   #表自身信息（元信息）
        db_table='user'

django05/App/forms.py
# -*- coding: utf-8 -*-
# @File    : forms.py
# 描述     ：
# @Time    : 2020/2/11 15:00
# @Author  :
# @QQ
from django import forms
import re
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from App.models import User

def check_password(value):
    #re.I此匹配模式表示忽略大小写的情况下进行匹配
    if re.match(r'\d*$',value,re.I):
        raise ValidationError('密码不能是纯数字')

def check_phone(value):
    #re.I此匹配模式表示忽略大小写的情况下进行匹配
    if re.match(r'^1[3|4|5|7|8][0-9]{8}$',value):
        raise ValidationError('手机号格式有误')

# 注册表单，主要是针对html中表单提交的数据进行验证
class RegisterForm(forms.Form):
    username=forms.CharField(min_length=6,required=True,error_messages={'required':'用户名必须输入','min_length':'用户名长度不能小于6'})
    password=forms.CharField(min_length=6,max_length=12,required=True,
                             validators=[check_password],  #自定义验证函数
                             error_messages={'required': '密码必须输入', 'min_length':'密码长度不能小于6','max_length':'密码长度不能大于12'}
                             )
    confirm_password = forms.CharField(min_length=6, max_length=12, required=True,
                                       error_messages={'required': '密码必须输入', 'min_length': '密码长度不能小于6',
                                              'max_length': '密码长度不能大于12'}
                               )
    email=forms.EmailField(error_messages={'invalid':'邮箱格式不正确'})
    phone=forms.CharField(required=True,
                          validators=[check_phone],
                          error_messages={'required':'手机号必须输入'}
                          )

    #单个字段的验证方法
    #方法的名称格式：clean_字段名
    def clean_username(self):
        #获取用户名
        username=self.cleaned_data.get('username')
        #查询数据库
        #如果存在
        if User.objects.filter(username=username).first():
            raise ValidationError('用户名重复')

        #必须把正确数据返回
        return username

    #全局验证，设计多个字段
    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        #判断两者是否相等
        if password != confirm_password:
            #全局验证需给个提示字段，方便知道有误地方
            raise ValidationError({'confirm_password':["两次密码输入不一致"]})
        return self.cleaned_data

django05/App/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from App.forms import RegisterForm
from App.models import User
def login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)

        #生成响应对像
        res=HttpResponse('cookie')
        res.set_cookie('username',username,max_age=3*60*60)
        print(res)
        return res
    return render(request,'login.html')

def reply(request):
    # 获取cookie中的username键值对
    username = request.COOKIES.get('username')
    # username不为空就是登录过，否则未登录
    if username:
        return HttpResponse("发表评论")
    else:
        return redirect(reverse("App:login"))


def index(request):
    # 获取cookie
    username = request.COOKIES.get('username')
    print(username)
    return render(request,'index.html',context={'username':username})


def logout(request):
    # 生成响应对象HttpResponseRedirect
    res = redirect(reverse("App:home"))
    print(res)
    res.delete_cookie('username')
    return res

def register(request):
    if request.method=='POST':
        #验证数据
        #1、用提交过来的数据request.POST生成表单对象
        form=RegisterForm(request.POST)
        #2、通过form的is_valid来检测数据是否合格，合格返回True，不合格返回False
        if form.is_valid():
            print(form.cleaned_data)
            username=form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            phone=form.cleaned_data.get('phone')
            user=User(username=username,password=password,email=email,phone=phone)
            user.save()
            return HttpResponse('首页')
        else:
            return render(request,'register.html',locals())
    else:
        #get请求
        return render(request,'register.html')

django05/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if username %}
<p>
    欢迎{{ username }}  <a href="{% url 'App:logout' %}">退出登录</a>
</p>
{% else %}
    <p>
    你还没有登录，请先 <a href="{% url 'App:login' %}">登录</a>
    </p>
{% endif %}
</body>
</html>

django05/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cookie登录</title>
</head>
<body>
<form action="{% url 'App:login' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username"> <br>
    密码：<input type="password" name="password"> <br>
    <input type="submit">
</form>
</body>
</html>

django05/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'App:register' %}" method="post">
    {% csrf_token %}

    用户名:<input type="text" name="username"><span>{{ form.username.errors }}</span><br>
    密码:<input type="password" name="password"><span>{{ form.password.errors }}</span><br>
    确认密码： <input type="password" name="confirm_password"> <span>{{ form.confirm_password.errors }}</span> <br>
    email： <input type="text" name="email"><span>{{ form.email.errors }}</span> <br>
    phone： <input type="text" name="phone"><span>{{ form.phone.errors }}</span> <br>
    {{ form.errors }}
    <input type="submit">
</form>
</body>
</html>

django05/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户列表</title>
</head>
<body>
<table border="1" width="100%">
    <tr>
        <th>用户名</th>
        <th>密码</th>
        <th>性别</th>
    </tr>
    {% for user in users %}
        <tr>
            <td>{{user.username}}</td>
            <td>{{user.password}}</td>
            {% if user.sex == 1 %}
                <td>男</td>
            {% elif user.sex == 2 %}
                <td>女</td>
            {% else %}
                <td>未知</td>
            {% endif %}
        </tr>
    {% endfor %}
</table>
</body>
</html>