day8/App01/urls.py
from django.contrib import admin
from django.urls import path

from App01 import views
app_name = 'App01'
urlpatterns = [
    path('upload/',views.do_upload,name='upload'),
    path('sendone/',views.send_one,name='one'),
    path('sendmany/',views.send_many,name='many'),
    #富文本编辑
    path('edit/',views.edit,name='edit'),

]

day8/day08/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #站点管理的路由
    path('admin/', admin.site.urls),
    path('app01/',include("App01.urls")),

]

day8/App01/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    uid=models.AutoField(primary_key=True)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=128)
    email = models.CharField(max_length=200)

    class Meta:
        db_table = 'bbs_user'
        #表名对应的中文名
        verbose_name_plural='用户'

day8/App01/forms.py
# 自定义表单
from django import forms
import re

from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from App01.models import User


# def check_password(value):
#     """
#     验证密码是不是纯数字
#     :param value: 密码字符串
#     :return: 无
#     """
#     if re.match(r'\d*$',value,re.I):
#         raise ValidationError("密码不能是纯数字")


# 注册表单 表单主要是针对html中表单提交的数据进行验证
class RegisterForm(forms.Form):
    username = forms.CharField(label='用户名',min_length=3,required=True,
                                error_messages={'required':'用户名必须输入','min_length':'用户名长度不能小于3'}
                               )
    password = forms.CharField(min_length=3,
                               required=True,
                               validators=[RegexValidator(regex=r'\d*$', message="密码不能是纯数字",code='password')],  # 自定义验证函数
                               error_messages={'required':'密码必须输入','min_length':'密码长度必须大于3'}
                               )
    confirm_password = forms.CharField(min_length=3,
                               required=True,
                               error_messages={'required': '密码必须输入', 'min_length': '密码长度必须大于3'}
                               )
    email = forms.EmailField(error_messages={'invalid':'邮箱格式不正确'})

    # 单个字段的验证方法
    # 方法的名称格式：clean_字段名()
    def clean_username(self):
        # 获取用户名
        username = self.cleaned_data.get('username')
        # 查询数据库
        # 如果存在
        if User.objects.filter(username=username).first():
            raise ValidationError("用户名重复")
        # 必须把正确数据返回
        return username

    # 全局验证，涉及多个字段
    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        # 判断两者是否相等
        if password != confirm_password:
            raise ValidationError({'confirm_password':["两次密码输入不一致"]})
        return self.cleaned_data


#登录
class LoginForm(forms.Form):
    username=forms.CharField(required=True,error_messages={
        'required':'用户名必须输入'
    })
    password=forms.CharField()
    captcha=CaptchaField()   #验证码字段

day8/App01/views.py
import os

from django.core.mail import send_mail, send_mass_mail, EmailMultiAlternatives
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
from django.template import loader

from day08.settings import MEDIA_ROOT, EMAIL_HOST_USER


def do_upload(request):
    if request.method=='POST':
        #1、获取文件上传对象
        file_obj=request.FILES.get('photo')

        #检验上传文件是否符合要求
        from App01.uploadfile import Upload
        fupload=Upload(MEDIA_ROOT,ext=['jpg','jpeg','png'])
        res=fupload.load(file_obj)
        if isinstance(res,str):
            return HttpResponse(res)
        else:
            return HttpResponse('上传成功')

    return render(request,'App01/upload.html')


def send_one(request):
    send_mail('加油','房子',EMAIL_HOST_USER,['515269984@qq.com'])
    return HttpResponse('发送一封成功')

def send_many(request):
    # mail1=('油','房子',EMAIL_HOST_USER,['515269984@qq.com'])
    # mail2 = ('买油', '房子', EMAIL_HOST_USER, ['chenggai0310@126.com'])
    # send_mass_mail((mail1,mail2))

    # 发送html邮件
    subject1, from_mail, to = ("女足", EMAIL_HOST_USER, ['313728420@qq.com'])
    content = loader.get_template("app01/sport.html").render()
    obj = EmailMultiAlternatives(subject1, from_email=from_mail, to=to)
    obj.attach_alternative(content, 'text/html')
    obj.send()
    return HttpResponse('发送多封成功')

def edit(request):
    if request.method=='POST':
        content=request.POST.get('content')
        return HttpResponse(content)
    return render(request,'App01/edit.html')

day8/templates/App01/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="/static/tiny_mce/tiny_mce.js"></script>

    <script>
        tinyMCE.init({
            'mode':'textareas',
            'width':800,
            'height':600,
        })
    </script>
    <title>富文本编辑</title>
</head>
<body>
<form action="{% url 'App01:edit' %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" cols="30" rows="10"></textarea> <br>
    <input type="submit">
</form>
</body>
</html>

day8/templates/App01/sport.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>测试邮件</h1>
</body>
</html>

day8/templates/App01/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文件上传</title>
</head>
<body>
<form action="{% url 'App01:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="photo">
    <input type="submit" value="上传">
</form>
</body>
</html>