day7/App01/urls.py
from django.contrib import admin
from django.urls import path

from App01 import views
app_name = 'App01'
urlpatterns = [
    path('register/',views.register,name='register'),
    #第三方验证码
    path('verify/', views.verify, name='verify'),
    #发送短信验证码
    path('sms/', views.send_sms, name='sms'),
    #短信登录
    path('smslogin/', views.sms_login, name='smslogin'),
]

day7/app02/urls.py
from django.contrib import admin
from django.urls import path

from app02 import views
app_name = 'app02'
urlpatterns = [
    path('list/',views.list_user,name='list'),
    path('list/<int:page>/',views.list_user,name='list'),
]

day7/day07/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/',include("App01.urls")),
    path('app02/',include("app02.urls")),
    #在跟路由添加验证码的路由
    path('captcha/',include("captcha.urls")),
]

day7/App01/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=128)

    class Meta:
        db_table = 'user'

day7/app02/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    uid = models.AutoField(primary_key=True)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=128, db_column='password_hash')

    class Meta:
        db_table = 'bbs_user'

day7/App01/forms.py
# 自定义表单
from django import forms
import re

from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from App01.models import User


# def check_password(value):
#     """
#     验证密码是不是纯数字
#     :param value: 密码字符串
#     :return: 无
#     """
#     if re.match(r'\d*$',value,re.I):
#         raise ValidationError("密码不能是纯数字")


# 注册表单 表单主要是针对html中表单提交的数据进行验证
class RegisterForm(forms.Form):
    username = forms.CharField(label='用户名',min_length=3,required=True,
                                error_messages={'required':'用户名必须输入','min_length':'用户名长度不能小于3'}
                               )
    password = forms.CharField(min_length=3,
                               required=True,
                               validators=[RegexValidator(regex=r'\d*$', message="密码不能是纯数字",code='password')],  # 自定义验证函数
                               error_messages={'required':'密码必须输入','min_length':'密码长度必须大于3'}
                               )
    confirm_password = forms.CharField(min_length=3,
                               required=True,
                               error_messages={'required': '密码必须输入', 'min_length': '密码长度必须大于3'}
                               )
    email = forms.EmailField(error_messages={'invalid':'邮箱格式不正确'})

    # 单个字段的验证方法
    # 方法的名称格式：clean_字段名()
    def clean_username(self):
        # 获取用户名
        username = self.cleaned_data.get('username')
        # 查询数据库
        # 如果存在
        if User.objects.filter(username=username).first():
            raise ValidationError("用户名重复")
        # 必须把正确数据返回
        return username

    # 全局验证，涉及多个字段
    def clean(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        # 判断两者是否相等
        if password != confirm_password:
            raise ValidationError({'confirm_password':["两次密码输入不一致"]})
        return self.cleaned_data


#登录
class LoginForm(forms.Form):
    username=forms.CharField(required=True,error_messages={
        'required':'用户名必须输入'
    })
    password=forms.CharField()
    captcha=CaptchaField()   #验证码字段

day7/app02/forms.py
# 自定义表单
import re

from django import forms
from django.core.exceptions import ValidationError

from App01.models import User


def check_password(value):
    '''
    验证密码是不是纯数字
    :param value: 密码字符串
    :return:
    '''
    if re.match(r'\d*$',value,re.I):
        raise ValidationError('密码不能是纯数字')


# 注册表单，表单主要针对html中表单提交过来的数据进行验证
class RegisterForm(forms.Form):
    username=forms.CharField(label='用户名',min_length=3,required=True,
                             error_messages={'required':'请输入用户名','min_length':'长度最少3个字符'})
    password=forms.CharField(label='密码',min_length=3,required=True,
                             validators=[check_password],  # 自定义验证函数
                             error_messages={'min_length':'密码长度不能小于3','required':'密码不能为空'}
                                 )
    confirm_password = forms.CharField(label='验证密码',min_length=3, required=True,
                               error_messages={'min_length': '密码长度不能小于3', 'required': '密码不能为空'}
                               )
    email=forms.EmailField(error_messages={'invalid':'邮箱格式不正确'})

    #单个字段验证方法,必须以clean_开头+验证的字段名
    def clean_username(self):
        #获取用户名
        username=self.cleaned_data.get('username')
        # 查询数据库
        if User.objects.filter(username=username).first():
            raise ValidationError('用户名重复')
        #必须把正确数据返回
        return username

    #全局验证，涉及多个字段，必须使用clean
    def clean(self):
        password=self.cleaned_data.get('password')
        confirm_password=self.cleaned_data.get('confirm_password')

        #两者判等
        if password!=confirm_password:
            raise ValidationError('两次密码不一致')
        #必须返回所有验证过的数据
        return self.cleaned_data

day7/App01/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from App01.forms import RegisterForm
from App01.models import User


def register(request):
    if request.method == 'POST':
        # 验证数据
        #1 用提交过来的数据request.POST生成表单对象
        form = RegisterForm(request.POST)
        # 2 通过form的is_valid来检测数据是否合格，合格返回True，不合格返回False
        if form.is_valid():
            print(form.cleaned_data.get('username'))
            print(form.cleaned_data)
            return HttpResponse("首页")
        else:
            print(form.errors)
            return render(request, 'App01/register.html', locals())
    else:
        return render(request,'App01/register.html')

def verify(request):

    if request.method=='POST':
        form=LoginForm(request.POST)
        #验证
        if form.is_valid():
            return HttpResponse("验证通过")
        else:
            return render(request,'App01/login.html')
    form=LoginForm()
    return render(request,'App01/login.html',locals())

def send_sms(request):
    from App01.SMS import sms
    from random import randint
    if request.is_ajax():
        phone=request.POST.get('phone')
        code=randint(1000,9999)
        request.session['code']=code
        request.session.set_expiry(5 * 60)  #5分钟内有效
        param="{'number':%d}" % code
        res=sms.send(phone,param)
        print(code,phone)
        return JsonResponse({'code':1})
    else:
        code=randint(1000,9999)
        param = "{'number':%d}" % code
        res = sms.send('13718234629', param)
        print(res)
        print(type(res))
        return HttpResponse(f'已发送{code}')

def sms_login(request):
    if request.method == 'POST':
        # 验证短信验证码
        yzm = request.POST.get('yzm')
        # 从session获取存入验证码
        code = str(request.session.get('code'))
        print(code, yzm)
        print(type(code), type(yzm))
        if yzm == code:
            return HttpResponse("验证成功")
    return render(request,'App01/sms.html')

day7/app02/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from day07.settings import COUNT_OF_PAGE
from app02.models import User


def list(request,page=1):
   data=User.objects.all()
   #生成分页器
   paginator=Paginator(data,COUNT_OF_PAEG)
   #获取分页对象
   pager=paginator.page(int(page))
   return render(request,'app02/list.html',context={
      'pages':pager,
      'page_range':paginator.page_range
   })

day7/templates/App01/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="{% url 'App01:verify' %}" method="post">
    {% csrf_token %}
    用户名:<input type="text" name="username"><span>{{form.username.errors.0}}</span><br>
    密码:<input type="password" name="password"> <br>
    验证码:{{ form.captcha }}<span>{{form.captcha.errors.0}}</span><br>
    <input type="submit">


</form>
</body>
</html>

day7/templates/App01/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="{% url 'App01:register' %}" method="post">
    {% csrf_token %}

{#    自定义表单字段，字段名必须和表单（forms中）字段名一致   #}
    用户名：<input type="text" name="username">
    <span>
        {% for error in form.username.errors %}
            <span>{{error}}</span>
        {% endfor %}
    </span> <br>
    密码： <input type="password" name="password">
    <span>
        {% for error in form.password.errors %}
            <span>{{error}}</span>
        {% endfor %}
    </span> <br>
    确认密码： <input type="password" name="confirm_password">
    <span>
        {% for error in form.confirm_password.errors %}
            <span>{{error}}</span>
        {% endfor %}
    </span> <br>
    email： <input type="text" name="email">
    <span>
        {% for error in form.email.errors %}
            <span>{{error}}</span>
        {% endfor %}
    </span> <br>

    <input type="submit">
</form>
</body>
</html>

day7/templates/App01/sms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>短信登录</title>
</head>
<body>
<form action="{{% url 'App:smslogin' %}}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username"> <br>
    密码：<input type="password" name="password"> <br>
    手机号：<input type="text" name="phone" id="phone"> <br>
    验证码：<input type="text" name="yzm"><input type="button" id='send' value="发送短信验证码"> <br>
    <input type="submit">
</form>
</body>
</html>
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script>
    $('#send').click(function(){
        num=5;
        $(this).attr('disabled',true);
        $(this).prop('value',''+num+'秒后发送')
        let _this=this;
        var timer=setInterval(function(){
            num-=1;
            if (num<=0){
                $(_this).attr('disabled',false);
                $(this).prop('value','发送验证码');
                return
            }
            $(_this).prop('value',''+num+'秒后发送')
            console.log(num)
        },1000);
        let phone=$('#phone').val();
        let csrf=$("[name='csrfmiddlewaretoken']").val();
        //发送短信验证码
        $.post("{% url 'App01:sms' %}",{'phone':phone,'csrfmiddlewaretoken':csrf},function(data){
            console.log(data)
        })
    })
</script>

day7/templates/app02/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="{% url 'app02:register' %}" method="post">
    {% csrf_token %}
{#    {{ form }}#}
{#    {{ form.as_p }}#}
{#    <table>#}
{#        {{ form.as_p }}#}
{#    </table>#}
{# 自定义表单字段，字段名必须和表单（form）一致#}
    用户名： <input type="text" name="username"> <span>{{ form.username.errors }}</span><br>
    密码：<input type="password" name="password"> <span>{{ form.password.errors }}</span><br>
    确认密码：<input type="password" name="confirm_password"> <span>{{ form.confirm_password.errors }}</span><br>
    email：<input type="text" name="email"> <span>{{ form.email.errors }}</span><br>
    <input type="submit">
</form>
</body>
</html>

day7/templates/list.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">


  </head>
  <body>
    <div class="container">
        <table class="table table-striped">
      <thead>
        <tr>
          <th>Last Name</th>
          <th>Username</th>
        </tr>
      </thead>
      <tbody>
      {% for user in pages.object_list %}
        <tr>
          <td>{{user.username}}</td>
          <td>{{ user.password }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    </div>
    <div class="container">
        {% for page in page_range %}
            <a href="{% url 'App02:list' page=page %}">{{ page }}</a>
        {% endfor %}
    </div>

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
  </body>
</html>